name: Build APK with Melange

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build APK
        uses: chainguard-dev/actions/melange-build@main
        with:
          config: build.yaml
          archs: x86_64

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v7
        with:
          path: /home/runner/work/os-build/os-build/packages/x86_64/*
